CREATE TABLE students (
    id uuid NOT NULL,
    username varchar(255) NOT NULL,
    kit_email varchar(255) NOT NULL,
    email_verified_at timestamp(6),
    credibility_score integer NOT NULL,
    status varchar(255) NOT NULL,
    biography text,
    last_seen_at timestamp(6),
    blocked_at timestamp(6),
    blocked_reason varchar(255),
    deleted_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_students PRIMARY KEY (id),
    CONSTRAINT uk_students_username UNIQUE (username),
    CONSTRAINT uk_students_kit_email UNIQUE (kit_email)
);

CREATE TABLE professors (
    id uuid NOT NULL,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    is_active boolean NOT NULL,
    average_rating numeric(3, 2) NOT NULL,
    rating_count integer NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT pk_professors PRIMARY KEY (id)
);

CREATE TABLE lectures (
    id uuid NOT NULL,
    name varchar(255) NOT NULL,
    code varchar(255),
    semester_year integer NOT NULL,
    semester_season varchar(255) NOT NULL,
    is_active boolean NOT NULL,
    lecture_type varchar(255) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT pk_lectures PRIMARY KEY (id)
);

CREATE TABLE admins (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT pk_admins PRIMARY KEY (id),
    CONSTRAINT uk_admins_student_id UNIQUE (student_id),
    CONSTRAINT fk_admins_student FOREIGN KEY (student_id) REFERENCES students (id)
);

CREATE TABLE auth_rate_limit_buckets (
    id uuid NOT NULL,
    operation varchar(40) NOT NULL,
    subject_hash varchar(64) NOT NULL,
    window_started_at timestamp(6) NOT NULL,
    attempts integer NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT pk_auth_rate_limit_buckets PRIMARY KEY (id),
    CONSTRAINT auth_rate_limit_operation_subject_key UNIQUE (operation, subject_hash)
);

CREATE TABLE one_time_passwords (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    hash text,
    value text,
    used boolean NOT NULL,
    expires_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT pk_one_time_passwords PRIMARY KEY (id)
);

CREATE TABLE tokens (
    id uuid NOT NULL,
    email varchar(255) NOT NULL,
    student_id uuid,
    hash text,
    value text,
    expires_at timestamp(6) NOT NULL,
    session_type varchar(255),
    revoked boolean NOT NULL,
    CONSTRAINT pk_tokens PRIMARY KEY (id),
    CONSTRAINT fk_tokens_student FOREIGN KEY (student_id) REFERENCES students (id)
);

CREATE TABLE lecture_professors (
    lecture_id uuid NOT NULL,
    professor_id uuid NOT NULL,
    CONSTRAINT pk_lecture_professors PRIMARY KEY (lecture_id, professor_id),
    CONSTRAINT fk_lecture_professors_lecture FOREIGN KEY (lecture_id) REFERENCES lectures (id),
    CONSTRAINT fk_lecture_professors_professor FOREIGN KEY (professor_id) REFERENCES professors (id)
);

CREATE TABLE ratings (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    lecture_id uuid NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_ratings PRIMARY KEY (id),
    CONSTRAINT uk_ratings_student_lecture UNIQUE (student_id, lecture_id),
    CONSTRAINT fk_ratings_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_ratings_lecture FOREIGN KEY (lecture_id) REFERENCES lectures (id)
);

CREATE TABLE rating_topics (
    id uuid NOT NULL,
    category varchar(255) NOT NULL,
    value double precision NOT NULL,
    rating_id uuid NOT NULL,
    CONSTRAINT pk_rating_topics PRIMARY KEY (id),
    CONSTRAINT uk_rating_topics_rating_category UNIQUE (rating_id, category),
    CONSTRAINT fk_rating_topics_rating FOREIGN KEY (rating_id) REFERENCES ratings (id)
);

CREATE TABLE comments (
    id uuid NOT NULL,
    content text NOT NULL,
    status varchar(255) NOT NULL,
    student_id uuid NOT NULL,
    lecture_id uuid NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_comments_lecture FOREIGN KEY (lecture_id) REFERENCES lectures (id)
);

CREATE TABLE answers (
    id uuid NOT NULL,
    content text NOT NULL,
    status varchar(255) NOT NULL,
    student_id uuid NOT NULL,
    comment_id uuid NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_answers PRIMARY KEY (id),
    CONSTRAINT fk_answers_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_answers_comment FOREIGN KEY (comment_id) REFERENCES comments (id)
);

CREATE TABLE comment_votes (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    comment_id uuid NOT NULL,
    vote varchar(255) NOT NULL,
    CONSTRAINT pk_comment_votes PRIMARY KEY (id),
    CONSTRAINT uk_comment_votes_student_comment UNIQUE (student_id, comment_id),
    CONSTRAINT fk_comment_votes_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_comment_votes_comment FOREIGN KEY (comment_id) REFERENCES comments (id)
);

CREATE TABLE answer_votes (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    answer_id uuid NOT NULL,
    vote varchar(255) NOT NULL,
    CONSTRAINT pk_answer_votes PRIMARY KEY (id),
    CONSTRAINT uk_answer_votes_student_answer UNIQUE (student_id, answer_id),
    CONSTRAINT fk_answer_votes_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_answer_votes_answer FOREIGN KEY (answer_id) REFERENCES answers (id)
);

CREATE TABLE comment_reports (
    id uuid NOT NULL,
    reason varchar(255) NOT NULL,
    explanation varchar(255),
    status varchar(255) NOT NULL,
    reporter_id uuid NOT NULL,
    comment_id uuid NOT NULL,
    reviewed_by_admin_id uuid,
    reviewed_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_comment_reports PRIMARY KEY (id),
    CONSTRAINT uk_comment_reports_reporter_comment UNIQUE (reporter_id, comment_id),
    CONSTRAINT fk_comment_reports_reporter FOREIGN KEY (reporter_id) REFERENCES students (id),
    CONSTRAINT fk_comment_reports_comment FOREIGN KEY (comment_id) REFERENCES comments (id),
    CONSTRAINT fk_comment_reports_reviewed_by FOREIGN KEY (reviewed_by_admin_id) REFERENCES admins (id)
);

CREATE TABLE answer_reports (
    id uuid NOT NULL,
    reason varchar(255) NOT NULL,
    explanation varchar(255),
    status varchar(255) NOT NULL,
    reporter_id uuid NOT NULL,
    answer_id uuid NOT NULL,
    reviewed_by_admin_id uuid,
    reviewed_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_answer_reports PRIMARY KEY (id),
    CONSTRAINT uk_answer_reports_reporter_answer UNIQUE (reporter_id, answer_id),
    CONSTRAINT fk_answer_reports_reporter FOREIGN KEY (reporter_id) REFERENCES students (id),
    CONSTRAINT fk_answer_reports_answer FOREIGN KEY (answer_id) REFERENCES answers (id),
    CONSTRAINT fk_answer_reports_reviewed_by FOREIGN KEY (reviewed_by_admin_id) REFERENCES admins (id)
);

CREATE TABLE bug_reports (
    id uuid NOT NULL,
    title varchar(255) NOT NULL,
    description text NOT NULL,
    severity varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    reporter_id uuid,
    resolved_by_admin_id uuid,
    resolved_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    issue_url varchar(255),
    issue_iid integer,
    issue_state varchar(255) DEFAULT 'NONE' NOT NULL,
    CONSTRAINT pk_bug_reports PRIMARY KEY (id),
    CONSTRAINT fk_bug_reports_reporter FOREIGN KEY (reporter_id) REFERENCES students (id),
    CONSTRAINT fk_bug_reports_resolved_by FOREIGN KEY (resolved_by_admin_id) REFERENCES admins (id)
);

CREATE TABLE warnings (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    admin_id uuid NOT NULL,
    message text NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT pk_warnings PRIMARY KEY (id),
    CONSTRAINT fk_warnings_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_warnings_admin FOREIGN KEY (admin_id) REFERENCES admins (id)
);

CREATE TABLE notifications (
    id uuid NOT NULL,
    recipient_id uuid NOT NULL,
    lecture_id uuid,
    own_comment_id uuid,
    type varchar(255),
    answer_id uuid,
    message text,
    seen boolean NOT NULL,
    created_at timestamp(6),
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES students (id),
    CONSTRAINT fk_notifications_lecture FOREIGN KEY (lecture_id) REFERENCES lectures (id),
    CONSTRAINT fk_notifications_own_comment FOREIGN KEY (own_comment_id) REFERENCES comments (id),
    CONSTRAINT fk_notifications_answer FOREIGN KEY (answer_id) REFERENCES answers (id)
);

CREATE TABLE audit_logs (
    id uuid NOT NULL,
    action varchar(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    actor_type varchar(20) NOT NULL,
    actor_id uuid NOT NULL,
    actor_name varchar(255) NOT NULL,
    actor_email varchar(255) NOT NULL,
    actor_role varchar(40) NOT NULL,
    target_type varchar(40),
    target_id uuid,
    target_label text,
    changes json NOT NULL,
    metadata json NOT NULL,
    reverts_audit_id uuid,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE INDEX idx_tokens_student_id ON tokens (student_id);
CREATE INDEX idx_ratings_lecture_id ON ratings (lecture_id);
CREATE INDEX idx_comments_lecture_id ON comments (lecture_id);
CREATE INDEX idx_answers_comment_id ON answers (comment_id);
CREATE INDEX idx_comment_reports_status ON comment_reports (status);
CREATE INDEX idx_answer_reports_status ON answer_reports (status);
CREATE INDEX idx_bug_reports_status ON bug_reports (status);
CREATE INDEX idx_audit_logs_created_at_id ON audit_logs (created_at, id);
